# Generated by Django 2.0 on 2021-01-23 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='diskdevice',
        ),
        migrations.RemoveField(
            model_name='host',
            name='distribution_version',
        ),
        migrations.RemoveField(
            model_name='host',
            name='processor_count',
        ),
        migrations.RemoveField(
            model_name='host',
            name='swaptotal_mb',
        ),
    ]
