# Generated by Django 2.0 on 2021-01-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20210123_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='distribution',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='host',
            name='os_family',
            field=models.CharField(default='', max_length=20),
        ),
    ]
